
-- Add fee columns to orders table
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_fee DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS service_fee DECIMAL(10,2) DEFAULT 0.00;

-- Create settings table for global configurations
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_fee DECIMAL(10,2) DEFAULT 5.00,
    commission_tiers JSONB DEFAULT '[
        {"max": 50, "percent": 10},
        {"max": 150, "percent": 7},
        {"max": 999999, "percent": 5}
    ]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default settings row if not exists
INSERT INTO public.settings (delivery_fee)
SELECT 5.00
WHERE NOT EXISTS (SELECT 1 FROM public.settings);

-- Enable RLS for settings (public read, admin write)
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.settings
    FOR SELECT USING (true);

CREATE POLICY "Enable update for admins" ON public.settings
    FOR UPDATE USING (true); -- Ideally restrict to admin role, but for now open for this user context
