-- Create commission_payouts table to track payments to the owner/admin
CREATE TABLE IF NOT EXISTS public.commission_payouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_date DATE NOT NULL, -- The specific day being paid out
    amount DECIMAL(10,2) NOT NULL, -- Total amount paid for that day
    status TEXT DEFAULT 'paid', -- 'paid'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.commission_payouts ENABLE ROW LEVEL SECURITY;

-- Policies (Admin only, essentially)
CREATE POLICY "Enable read access for all users" ON public.commission_payouts
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for admins" ON public.commission_payouts
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for admins" ON public.commission_payouts
    FOR UPDATE USING (true);

-- Index for quick lookups by date
CREATE INDEX IF NOT EXISTS "commission_payouts_date_idx" ON public.commission_payouts ("reference_date");
