-- Create a table for global store settings
CREATE TABLE IF NOT EXISTS store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stripe_account_id TEXT,
    stripe_details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert initial row if empty
INSERT INTO store_settings (id)
SELECT 1
WHERE NOT EXISTS (SELECT 1 FROM store_settings WHERE id = 1);

-- Enable RLS
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone (public) - needed for Checkout to know if stripe is enabled
CREATE POLICY "Public can view store settings" ON store_settings
    FOR SELECT USING (true);

-- Allow update access only to authenticated users (admins) implies admin role or logged in
-- For MVP, assuming any logged in user is admin or we trust the app's auth
CREATE POLICY "Admins can update store settings" ON store_settings
    FOR UPDATE USING (auth.role() = 'authenticated');
