-- 1. Add is_combo column to products
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_combo BOOLEAN DEFAULT FALSE;

-- 2. Create combo_items table
CREATE TABLE IF NOT EXISTS combo_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    child_product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    -- Prevent duplicate links between same parent/child
    CONSTRAINT unique_combo_link UNIQUE (parent_product_id, child_product_id)
);

-- Enable RLS
ALTER TABLE combo_items ENABLE ROW LEVEL SECURITY;

-- Policies for combo_items
CREATE POLICY "Public read combo items" ON combo_items FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admin manage combo items" ON combo_items FOR ALL TO service_role USING (true);

-- 3. Trigger Function for Stock Deduction
-- SECURITY DEFINER allows this function to bypass RLS and update products even if the user is anonymous
CREATE OR REPLACE FUNCTION handle_order_stock_deduction()
RETURNS TRIGGER 
SECURITY DEFINER 
SET search_path = public
AS $$
DECLARE
    is_combo_item BOOLEAN;
    child RECORD;
BEGIN
    -- Check if the product is a combo
    -- We can Select into a boolean directly
    SELECT is_combo INTO is_combo_item FROM products WHERE id = NEW.product_id;

    IF is_combo_item THEN
        -- If it is a combo, deduct stock from all child products
        FOR child IN SELECT * FROM combo_items WHERE parent_product_id = NEW.product_id LOOP
            UPDATE products
            SET stock_quantity = stock_quantity - (NEW.quantity * child.quantity)
            WHERE id = child.child_product_id;
        END LOOP;
    ELSE
        -- If it is a simple product, deduct from itself
        UPDATE products
        SET stock_quantity = stock_quantity - NEW.quantity
        WHERE id = NEW.product_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Create Trigger
DROP TRIGGER IF EXISTS tr_deduct_stock ON order_items;
CREATE TRIGGER tr_deduct_stock
AFTER INSERT ON order_items
FOR EACH ROW
EXECUTE FUNCTION handle_order_stock_deduction();

-- 5. Optional: Helper to calculate available stock for a combo dynamically
-- This can be used in your application logic or views
CREATE OR REPLACE FUNCTION get_combo_stock(combo_id BIGINT)
RETURNS INTEGER 
STABLE
AS $$
DECLARE
    min_stock INTEGER;
BEGIN
    SELECT MIN(floor(p.stock_quantity / ci.quantity)::INTEGER)
    INTO min_stock
    FROM combo_items ci
    JOIN products p ON p.id = ci.child_product_id
    WHERE ci.parent_product_id = combo_id;

    RETURN COALESCE(min_stock, 0);
END;
$$ LANGUAGE plpgsql;
